### ISSUE TITLE
目录自动生成的序号在哪里去除呢？给人很杂乱的感觉

### ISSUE THREAD

**Issue by op134972** [iissnan/hexo-theme-next#1553]

**Comment by jetyu** [comment]
以前貌似没这个问题

**Comment by skyue** [comment]
主题配置文件下有个`toc`选项，将其下的`number`设置为`false`应该就行了。

```
# Table Of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: false
```

**Comment by ivan-nginx** [comment]
@op134972 problem is solved?

**Comment by op134972** [comment]
@ivan-nginx yeah

**Comment by Yalhu** [comment]
I still have this problem server on localhost:4000. And I doesn't deploy it yet.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
