### ISSUE TITLE
Outline list rendering is incorrect

### ISSUE THREAD

**Issue by BarryLiu1995** [iissnan/hexo-theme-next#1771]
### Expected behavior (预期行为)
![right rendering](http://image.jiantuku.com/17-7-19/99923270.jpg?attname=file_1500438399891_db10.jpg&e=1500439210&token=el7kgPgYzpJoB23jrChWJ2gV3HpRl0VCzFn8rKKv:_MGB32AtJ7f6z1Ao77OmlrdXMxA=)

### Actual behavior (实际行为)
![wrong outline](https://user-images.githubusercontent.com/20590350/28400050-662c4782-6d43-11e7-9899-422b8e57523b.jpg)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔-  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  ✔-  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
win10 chrome 
![screenshot](http://image.jiantuku.com/17-7-19/5244932.jpg?attname=file_1500438400032_2af9.jpg&e=1500439210&token=el7kgPgYzpJoB23jrChWJ2gV3HpRl0VCzFn8rKKv:-nOARO9d-tZiPbZr5pA2dSjIEAc=)

**Comment by ivan-nginx** [comment]
@BarryLiu1995 `hexo clean && hexo g`?

**Comment by BarryLiu1995** [comment]
@ivan-nginx I did it!But it doesn't work at all

**Comment by ivan-nginx** [comment]
@BarryLiu1995 can u explain what else u did with template files? As i see, `File` and `Outline` is non-standart labels. And explain in what is trouble? I only see screens at all and nothing else. Can u explain what u want? And can u show live demo?

**Comment by Neveryu** [comment]
每一个 markdown 的解析器对于目录的解析是不一样的，你不能要求你在别的解析器上面解析出来的目录，能一模一样的出现在 hexo&NexT 中。
so ， you should

**Comment by BarryLiu1995** [comment]
@Neveryu 我知道每个md解析器对目录的解析是不一样的，但是感觉next主题下的解析目录出现了逻辑上的错误，我并不要求解析效果一模一样，只是感觉这解析逻辑出问题了

**Comment by ivan-nginx** [comment]
@BarryLiu1995 and i think what is not Next theme bug, if trouble in Markdown rendering. What u think?

**Comment by BarryLiu1995** [comment]
@ivan-nginx Hello, first thanks for your help. I mean the Outline rendering has a logical error. I use Typora editor to write my blog and you can see Outline rendering result in **"Expected behavior"**. But when I finish `hexo clean` and `hexo g -d` commands and the Outline rendering result which you can see in **"Actual behavior"** happen in my Blog website has a logical error. Maybe just like what you said, the trouble has nothing to do with Next theme because I had met the same problem in other Hexo themes.

**Comment by ivan-nginx** [comment]
@BarryLiu1995 i don't understand u again: issue is solved or not?

**Comment by BarryLiu1995** [comment]
@ivan-nginx The problem is not resolved. Different levels of title in outline are not displayed correctly. I have tried to clean up the cache

**Comment by ivan-nginx** [comment]
Can u plase show live demo? And source code. I just don't understand where u get style from screen in "Expected behavior". This is Next theme with modified files or what?

**Comment by BarryLiu1995** [comment]
this is markdown file in yourwebsite/source/posts file path
## Here is small part of markdown source code
![source code](https://user-images.githubusercontent.com/20590350/28402091-87733eac-6d50-11e7-91ff-0e15f3ef2623.jpg)
## Here is markdown grammar
![markdown grammar](https://user-images.githubusercontent.com/20590350/28402132-ccc3dc00-6d50-11e7-977d-55a50d250053.jpg)
## Here is outline
![outline](https://user-images.githubusercontent.com/20590350/28402155-ea95f510-6d50-11e7-9edb-8623dc8c68c8.jpg)

**Comment by BarryLiu1995** [comment]
@ivan-nginx look back!

**Comment by ivan-nginx** [comment]
1. Can u give not screen of md source? Just give link on source code from github or attach it with txt file here.
2. I still not see live demo of the blog.
3. Can u explain why u use h4 after h2? This bad for seo, take it mind.

**Comment by BarryLiu1995** [comment]
1.[my blog source code repository](https://github.com/BarryLiu1995/BarryLiu1995.github.io.git)
[the blog address](http://barryliu1995.studio/2017/07/12/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0(%E4%BA%8C)/#more)

3.ok, I will modify！

**Comment by ivan-nginx** [comment]
@BarryLiu1995 > 1.my blog source code repository
This is not source. This generated `*.html` files for web. Source must include `*.md` files, what u show my on screens.

**Comment by BarryLiu1995** [comment]
@ivan-nginx  I upload the `.md` [file](https://drive.google.com/open?id=0B3bw_DtQ3uVOS0tYLVJ1aloxc1k) to google drive. Please check!
the `File` & `Outline` is [Typora](https://www.typora.io/) editor's UI

**Comment by ivan-nginx** [comment]
@BarryLiu1995 so, the trouble in `1.0.1. CSS 注意事项` - after that TOC breaking?

**Comment by BarryLiu1995** [comment]
@ivan-nginx Yes!

**Comment by ivan-nginx** [comment]
@BarryLiu1995 idk what's wrong with your Hexo or Next, but i reproducte [your MD in my test blog](http://test.almostover.ru/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0(%E4%BA%8C)/) and my TOC is worked fine.

Try to:
1. Install latest Hexo & Next theme and generate your `*.md` without any plugins.
2. Change Next scheme to another (e.g. Pisces).
3. Turn off any comments and remove `comment: true` from `*.md` file.

**Comment by BarryLiu1995** [comment]
@ivan-nginx  I use h3 after h2 and it did well. Maybe this is the problem!

**Comment by ivan-nginx** [comment]
Yep, headers must strongly be with after another, and vice versa.

U must use:
```
H2
  H3
H2
  H3
    H4

H2
  H3
    H4
  H3
    H4
      H5
    H4
      H5
        H6
...
```
Not use:
```
H2
      H4
    H3
```
this is wrong usage and very bad for SEO. U may see my oldest post about headers [here](https://almostover.ru/2016-08/fix-h1-to-h2-headings-in-posts-of-hexo-themes/).
```
 If solved, close it.
